# Uncomment the next line to define a global platform for your project
platform :osx, '13.1'

target 'Crawler' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crawler
  pod 'SwiftSoup'
end
